### ISSUE TITLE
Formatter must never format arrays as `null`

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/ocean#171]
```D
void main ()
{
    int[] arr;
    Stdout.print(format("{}\n", arr));

    arr = new int[5];
    arr.length = 0;
    Stdout.print(format("{}\n", arr));
}
```

This code must print `[]` twice. Right now it has special case for `arr.ptr is null` and will print `null` for a first call.

As this is a subtle breaking change, scheduling it to v4.0.0 for now.

**Comment by mihails-strasuns-sociomantic** [comment]
FYI @mathias-lang-sociomantic

**Comment by andrej-mitrovic-sociomantic** [comment]
For `char[]` I expect it to print ` `, as in, nothing. That's the behavior of the old code.

**Comment by mathias-lang-sociomantic** [comment]
> This code must print `[]` twice. 

Why?

**Comment by mihails-strasuns-sociomantic** [comment]
Because D spec / implementation has no such notion as "null array", content of pointer is purely implementation detail. We know of some ways to guarantee it will ne null or non-null but it is not defined in general - this issue, for example, was brought to me by @andrej-mitrovic-sociomantic because of tests starting to fail depending on how variable is declared as they expect specific consistent formatting.

And, in general, I can't imagine why anyone would want to have an array printed as a pointer. In the code snippet above I create an empty array. I explicitly initialize it with `[]` literal. It is rather surprising to get anything else as a string representation. In my opinion `null` must be only used when printing pointers/classes and never with arrays/strings.

**Comment by mihails-strasuns-sociomantic** [comment]
NB: Original snipet used to start with `int[] arr = [ ]` but I forgot the literal when writing it here ;)

**Comment by mathias-lang-sociomantic** [comment]
> Because D spec / implementation has no such notion as "null array", content of pointer is purely implementation detail.

This is wrong. There's a difference between empty slices and null slices.
```D
void main ()
{
    int[] arr1 = [42];
    int[] arr2;
    foo(arr1[0..0]); // Pass
    foo(arr2);       // Fails
}

void foo (int[] arr)
{
    assert(arr);
}
```

And when a change to this was attempted, Andrei was explicitly against it and it was reverted.
Not to defend the spec in that regard - I am not a fan of this behavior - but the difference is clear and (nowadays) quite widely known.

> And, in general, I can't imagine why anyone would want to have an array printed as a pointer.

The correct terminology here would be reference. Slices, like classes, are reference types after all, and they are handled consistently.
If you look at the formatter code, you'll see there is nothing special to treat `null` arrays as `null`. But there is a portion of the code which checks for references types being `null`.

> In the code snippet above I create an empty array. I explicitly initialize it with `[]` literal. It is rather surprising to get anything else as a string representation.

What if you initialize it will `null` ? Won't you be surprised to see `[]` being printed ?

Note that I don't strongly oppose this change. This change of behavior have been the single point of contention for code switching to `Formatter`. But I also find the reasoning for doing so pretty moot.

**Comment by mihails-strasuns-sociomantic** [comment]
> This is wrong. There's a difference between empty slices and null slices.

There is no inherent language difference. You can see it via `arr.ptr` and it bites you in conditions (`if` or `assert`) because compiler rewrites slices to `slice.ptr` in boolean contexts (and that really sucks). But no place in spec (https://dlang.org/spec/arrays.html) talks about null arrays as something distinct or defines in what situations to expect them.

You can't even know for sure when compiler will init your array with `null` and when with zero-length pointer, it is completely implementation defined! @andrej-mitrovic-sociomantic had a nice snipper which I can't find anymore sadly.

> And when a change to this was attempted, Andrei was explicitly against it and it was reverted.

Yes, and this is still widely remembered as a case "when misfeature remained because whole 2 developers got used to rely on it". Fortunately, we don't have to keep in mind Andrei preferences in Sociomantic code.

The very fact that no place in spec defines when array is guaranteed to be `null` or not is a clear indicator that rewrite to `arr.ptr` was a rather bad idea.

> What if you initialize it will null ?

You should get warned during code review ;) I mean in the ideal world I would prefer to have all array literals strongly typed in clear way but using at least _some_ array literal seems reasonable common ground to me.

**Comment by don-clugston-sociomantic** [comment]
This also affects ``Logger``, which now has a silent change in behaviour compared to ``Log``:
```d
cstring s;
log.info("comments: {}", s);
```
prints "comments: null" to the log. This is wrong.  That's the same output you would get with
```d
cstring s = "null";
log.info("comments: {}", s);
```
This breaks several of our apps.

**Comment by mathias-lang-sociomantic** [comment]
@mihails-strasuns-sociomantic : We both know how complete the written specs is. In this case, there is a difference in [`IdentityExpression`](https://dlang.org/spec/expression.html#IdentityExpression), where it says both length and array content must match.

> This breaks several of our apps.

Just out of curiosity, how does the logger output breaks the app ? Do you have a script that parses log files ?

> That's the same output you would get with

Hum that would be a good reason to change it, indeed.

**Comment by don-clugston-sociomantic** [comment]
>Just out of curiosity, how does the logger output breaks the app ? Do you have a script that parses log files ?

In some modes of operation (a dry-run, essentially), the logs are actually the primary output of the app. These output files are actually used by non-D programmers to check for errors in the input data. That's a D2 blocker.

**Comment by nemanja-boric-sociomantic** [comment]
Semi-related: some implementations of `printf` would print `(null)` - literally, when passing `(char*)NULL` to `%s`. I always found this confusing and against what I would expect. IOW - I don't know why would anybody want to print null literary, except in some cases (say nullable column in database, where there's a clean distinction between empty string and null).

**Comment by david-eckardt-sociomantic** [comment]
> This is wrong. There's a difference between empty slices and null slices.

> There is no inherent language difference. You can see it via `arr.ptr` and it bites you in conditions (if or assert) because compiler rewrites slices to `slice.ptr` in boolean contexts (and that really sucks).

Yes and no.
- `null` arrays are a subset of empty arrays. I wouldn't call this a "difference between empty and `null` arrays" because...
- `null` arrays are empty just like any empty array. For the array content there is indeed no inherent language difference, both have the same content: None.
- But there is the keyword `null`. If you just want some empty array and use `null`, D gives you more than you're asking for and in addition guarantees the pointer is `null`, which is of no use for you, because, since the array is empty, the pointer doesn't matter. This `null` pointer guarantee is an inherent language difference to `[]` which really only specifies the length.
- What makes a difference is the result of `array is null`. `is` is a bitwise comparison: It yields `true` if all bits in `array` are 0. By itself this is a requirement not only for `array.ptr` but also for `array.length` But since by definition one cannot dereference a `null` pointer, `array.ptr is null` means `array.length` must be 0, which means `array is null`. Q.e.d.
- `array is null` is applied implicitly in boolean expressions such as `if (array)` or `assert(array)`. This is useful if the expression `array.ptr is null` carries meta-information such as "`array` is an uninitialised variable".

So I think it comes down to the last point, which is a matter of perspective: Does the expression `array.ptr is null`, which is equivalent to `array is null`, carry meta-information about the array that is interesting for the reader? For a person who or a program that is interested only in the *content* of the array, not the implementation detail of the array *variable* in the program that produced the output, it is superfluous information: It adds the unnecessary and potentially adverse complexity of two representations for an empty array -- `[]` and `null`.
