### ISSUE TITLE
StringC.toCString can be Inout

### ISSUE THREAD

**Issue by jens-mueller-sociomantic** [sociomantic-tsunami/ocean#182]
It should be possible to change `toCString` from
```d
public static char* toCString ( ref mstring str )
```

to

```d
public static Inout!(char)* toCString ( ref Inout!(char)[] str )
```

Because the implementation does not rely on `str` being mutable. Having it as `Inout` allows passing `cstring`s or even `istring`s.

Note this also applies to the `Wchar` overload.

**Comment by mihails-strasuns-sociomantic** [comment]
I don't think `str` can't be mutable here - the very point of this function is appending to _the very same string_ in-place which you are not allowed to do if it contains const elements. `ref` bit is important here.

Unless I misunderstand something?

**Comment by nemanja-boric-sociomantic** [comment]
Yes I think @mihails-strasuns-sociomantic is right. Only `toDString` can be inout, and they already are.

**Comment by jens-mueller-sociomantic** [comment]
I don't get it. Why are you not allowed to append to a `cstring`?

**Comment by mihails-strasuns-sociomantic** [comment]
You are allowed to append but it won't be in place, always resulting in allocating new GC root and abandoning original reference.

**Comment by jens-mueller-sociomantic** [comment]
Even if there is capacity left? So it is conservative because there might be others referencing this?

**Comment by mihails-strasuns-sociomantic** [comment]
Capacity in its regular sense is almost meaningless for const/immutable because you are not allowed to _ever_ overwrite immutable elements (and any const can be immutable in disguise). So only situation when already allocated GC chunk has some extra capacity to append in place is when tail of GC block was originally not used at all and your appended suffix is small enough to fit (as this memory is not yet "known" to type system).

**Comment by jens-mueller-sociomantic** [comment]
I see the point: all elements are read-only (even the ones accessible through appending) and there is only a very rare occasion when this can be violated.

**Comment by jens-mueller-sociomantic** [comment]
I reconsidered the issue because I believe we misunderstood. I wrote some test code. In my test code I am appending to an `mstring`, a `cstring` and an `istring`. I only append if their capacity is larger than their length. I verified that no GC allocation happens via `testNoAlloc`. To me this shows that you can append to a non-mutable string without allocation. So I still wonder why the signature of `toCString` requires `mstring`s when it could also work for `cstring`s and `istring`s.

Maybe it was my phrasing when I said

> Because the implementation does not rely on `str` being mutable.

What I wanted to express is that the implementation makes no assumptions on the type of the elements of `str`. As long as capacity is larger than length it will be in-place without allocation. The moment capacity is equal to length there is no way to append without reallocation. The `ref` in the signature is important to modify the caller's slice.

Does it make sense?

**Comment by mathias-lang-sociomantic** [comment]
Can you share your test code ?

**Comment by jens-mueller-sociomantic** [comment]
Try something like

```d
cstring a = "some".dup;
version(D_Version2) test(a.capacity > a.length);
else static assert(false);
testNoAlloc(a ~= "m");
```

`dup` will be only there in D2 as well. Didn't check for that.

**Comment by jens-mueller-sociomantic** [comment]
BTW another observation is that in D2 for string literals capacity seems to be `0`. This way you can handle that case without allocating since they are null terminated already.

**Comment by mathias-lang-sociomantic** [comment]
It only works in this specific case because the runtime knows it's safe. If you were to slice a to `a[0 .. 3]` it would allocate.

**Comment by jens-mueller-sociomantic** [comment]
You mean the literal testing. Yes, that is the case. So checking for capacity won't work. What about the general issue? To me there are cases where you can safe the allocation that the current implementation does not cover. I still don't see what you gain by disallowing those cases?

**Comment by mathias-lang-sociomantic** [comment]
> You mean the literal testing.

No, I mean:
```D
cstring origin = "some".dup;
cstring a = origin[0 .. 3];
version(D_Version2) test(a.capacity > a.length);
else static assert(false);
testNoAlloc(a ~= "m"); // Fails, obviously
```

Your code does not allocate not by design, but because of an optimization the runtime make. In the general case, you cannot guarantee appending will not allocate and you should not try to.

You actually hit a sweet spot here. Consider:

```D
    cstring a = "123456789ABCDEF".dup;
    version(D_Version2) test(a.capacity > a.length);
    else static assert(false);
    testNoAlloc(a ~= "m");
```

This will allocate. The reason is that the runtime allocates on a 16 bytes alignment.

**Comment by jens-mueller-sociomantic** [comment]
True. But this happens for the current implementation as well. If there is no room for the null byte it will need to allocate.
If you can show me how to avoid the allocation for `mstring`s which does not work for non-mutable strings, then I can see value in the current restriction of the signature.

**Comment by jens-mueller-sociomantic** [comment]
What do you loose when you change the parameter type from `mstring` to `Inout!(char)[]`? This is what I don't see.

**Comment by mathias-lang-sociomantic** [comment]
> What do you loose when you change the parameter type

Safety & readability. You are basically making the code harder to read, because one would have to look up how the parameter that was allocated ended up here, what size it was, if it is even possible to know, and if it is a slice of a larger buffer or not, for a minor convenience for the writer.

Currently there is not a single place in our code which assume appending to a `cstring` / `istring` won't reallocate. The buffer approach we use have been for very good reason.

Going back to your example, what prevents you for passing a mutable slice around ? Since you have to get a mutable slice at some point anyway.

**Comment by mihails-strasuns-sociomantic** [comment]
@jens-mueller-sociomantic so key thing about current `toCString` is that its argument is supposed to be a reusable buffer, something like this:

```D
void foo ( cstring original )
{
    static mstring buffer; // or a class field
    buffer.copy(original);
    c_func(toCString(buffer));
}
```

This can never be done with immutable strings. Yes, sometimes you can slip in that extra null byte because GC allocations are aligned and runtime knows you are the only owner of the slice (it is exactly the case I have mentioned in https://github.com/sociomantic-tsunami/ocean/issues/182#issuecomment-314072791), but it is not how `toCString` is intended to work and it is not something you can rely on in allocation-caring program.

Latter is essential. Ocean array/string utilities in general are not about occasional convenience, they provide strict and predictable guarantees about how memory is reused. If you care about memory allocations, you can accept nothing less. If you don't care, you can as well just append `\0` like we talked before. Trying to introduce some middle ground only compromises both.

**Comment by jens-mueller-sociomantic** [comment]
Alright. `toCString`s use case is different than what I'm looking for. Essentially `toCString`'s signature communicates that it expects a reusable buffer to enable appending without allocation which wasn't clear to me.

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah, this is pretty much standard for ocean API's - I think you may have been caught by surprise by different memory allocation requirements common in your team specifically ;)
