### ISSUE TITLE
Reduce CodeCov noise to signal ratio

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/ocean#208]
CodeCov as it is, is not being very useful, as we get red PRs that are OK.

I know there is #204, but it seems other project had issues with it, so maybe we can analyse taking similar [steps](https://github.com/dlang/druntime/pull/1874).

**Comment by mihails-strasuns-sociomantic** [comment]
I am not aware of any other issues other than related to #204 in our projects. When there are no unrelated files, codecov numbers match dmd -cov reports. Linked solution is hardly a solution at all because it essentially disables coverage checks completely.

Major problem is that dmd own -cov reporting is not very good and, for example, ignores all CTFE. But I am not sure we can do anything about it.

**Comment by stefan-koch-sociomantic** [comment]
@mihails-strasuns-sociomantic We can actually.
newCTFE has the ability (in therory)  to give you coverage for ctfe.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, so the main noise came from the flakey tests, so I guess we can close this one.
