### ISSUE TITLE
Adapt contiguous serializer to optionally accept reference types

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#248]
Currently, reference types are rejected, as the original intention was to serialize data for sending over the network. There are use cases for using the serializer purely in-memory, though. The serialization of request arguments into a buffer owned by a `Request` instance, in swarm neo, is one such case. Currently, we use a hack to convert reference types into static arrays (https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/client/mixins/RequestCore.d#L54-L67).

**Comment by gavin-norman-sociomantic** [comment]
@david-eckardt-sociomantic said:

AFAIR we need the following serializer modifications:
- accept all types
- shallow serialization of dynamic arrays, i.e. serialize the array reference only
  - I wonder if this is this really always true... for Swarm request parameters we may want to copy array contents.
- maintain alignment

Probably alignment would be the most difficult thing to integrate into the existing serializer; the other points greatly simplify it. Perhaps the solution with the cleanest code would be to write a separate serializer.

**Comment by david-eckardt-sociomantic** [comment]
> shallow serialization of dynamic arrays, i.e. serialize the array reference only
> I wonder if this is this really always true... for Swarm request parameters we may want to copy array contents.

I remember saying that, but in a certain context, which I don't remember... In general it is not always true.

> Probably alignment would be the most difficult thing to integrate into the existing serializer

Yes, alignment is difficult. It requires knowing the current position in the buffer of serialised data in order to add padding bytes. Consider
```d
struct S
{
    ubyte[] a;
    Object[] b;
}
```
After appending the content of `S.a` to the buffer padding bytes need to be inserted so that the elements of `S.b` are well aligned. Then the deserialiser needs to follow that, too, in order to skip the padding bytes. Finally the whole data buffer needs to be aligned, too, which is the case for `new`ed buffers but not necessarily if the buffer is a slice of a larger array (such as a queue buffer).

**Comment by gavin-norman-sociomantic** [comment]
I wonder whether it might make more sense to have two different serializers (ideally sharing some core of code): one for network serialization and one for in-memory serialization.

**Comment by gavin-norman-sociomantic** [comment]
As swarm request context packing is the only known use case for this proposal, I implemented something specialised in swarm (https://github.com/sociomantic-tsunami/swarm/pull/178). I think that's a better solution than trying to add functionality to the ocean serializer that would add complexity and dilute the concept.
