### ISSUE TITLE
Deprecate wchar[] and dchar[] supporting routines

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#279]
We have tons of (legacy) code which take `wchar` and `dchar` into account, which are types we don't use and never had.
According to [this comment](https://github.com/sociomantic-tsunami/ocean/pull/191#issuecomment-315309526) consensus was already reached:
> @mihails-strasuns-sociomantic 
> Is the wchar overload really necessary? I  thought concensus was that we never use those and should slowly strip  ocean code base from such overloads.

But it looks like there is no issue recording it, so adding one here.

**Comment by mihails-strasuns-sociomantic** [comment]
Pinging @sociomantic-tsunami/core-team to check if there are indeed no other opinions

**Comment by gavin-norman-sociomantic** [comment]
I've never seen 2+-byte chars used and agree that it'd be beneficial to strip out the code that supports them.

**Comment by leandro-lucarella-sociomantic** [comment]
Also +1 but I want to hear confirmations from @ben-palmer-sociomantic @stefan-brus-sociomantic @joseph-wakeling-sociomantic and @vasileios-kyrillidis-sociomantic too.

**Comment by stefan-brus-sociomantic** [comment]
Sounds good to me.

**Comment by leandro-lucarella-sociomantic** [comment]
#280 already merged, so marking as done.

**Comment by mathias-lang-sociomantic** [comment]
#280 says "part of", not "fixes" :P

**Comment by mihails-strasuns-sociomantic** [comment]
And relatively minor part I think :)

**Comment by mihails-strasuns** [comment]
Currently working on this - ended up being surprisingly problematic because of constness issues. Plenty of text utilities are supposed to propagate mutability to return type (anything that returns `*Fruct`) which one normally does with `inout`. But there is no way to define one of struct fields as `inout` which means it is inherently incompatible with `Fruct` approach - and that propagates up the call stack.

For now looks like best approach is a mix of templated internal and casts in the calling code.

**Comment by mihails-strasuns** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/687
