### ISSUE TITLE
Flawed design of `Scheduler.exception_handler`

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/ocean#451]
https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/task/Scheduler.d#L175 is a public field and expected to be customizable. However it will only work before the event loop was started because it is passes by value https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/task/Scheduler.d#L545-L550 here. This will cause mysterious failures if someone attempts to change the exception handler after event loop was started.

**Comment by gavin-norman-sociomantic** [comment]
So this is unrelated to https://github.com/sociomantic-tsunami/turtle/pull/36, right? (You just noticed this while investigating that?)

**Comment by mihails-strasuns-sociomantic** [comment]
It is semi-related in a sense that this issue is why turtle point release is needed and similar fix in the app code won't work (as they can't modify handler before event loop starts).

**Comment by don-clugston-sociomantic** [comment]
There is another problem which I have noticed. I am not sure if this is an independent issue, but it is a design problem with the exception handler.

The default exception handler catches the exception and rethrows it. I think this assumes that the calling fiber has a try-catch block which will handle that exception. 
But if the exception is not caught, there'll be a core dump. Unfortunately, the stack for the fiber which caused the exception has already been unwound. So the stack trace will begin from the moment when the exception is rethrown. This contains no useful information.

So, that's pretty annoying. By default, core dumps for uncaught exceptions are completely useless. But, the reason why it behaves this way is interesting.
Fundamentally, the idea of switching stacks while processing exceptions would need to be handled at a lower level. The runtime needs to know about fibers when it is walking the stack.

I don't know how it works in Linux but I do understand the Windows method, and I presume they're pretty similar. Exception handling has two passes, one where you walk the stack trying to find the target `catch` block, and then a second time when you walk the stack, unrolling it and executing the catch block. Switching stacks needs to be done in the first pass, but this code tries to do it only in the second. 

Catching and rethrowing looks superficially similar but it isn't quite right.

**Comment by david-eckardt-sociomantic** [comment]
AFAIK unhandled exceptions in a fiber coroutine are handled as follows: The actual fiber coroutine, `fiber_entryPoint`, calls the user coroutine in a `try/catch` block. If the user coroutine throws (i.e. terminates with an unhandled exception) `fiber_entryPoint` catches it, stores it in `Fiber.m_unhandled` and returns so that the fiber terminates. The resumed `Fiber.call` call then rethrows the exception.

I don't think the runtime needs to know about fibers when walking the stack, it will ultimately hit the `catch` clause in `fiber_entryPoint` without context switching.

**Comment by don-clugston-sociomantic** [comment]
> The resumed Fiber.call call then rethrows the exception.

That's the thing which is wrong. The call stack has been destroyed at that point. It needs to work out who will catch the exception, *before* it starts unwinding the stack.
(And if nobody will catch it, then it should die at that point. That's how exception handling is supposed to work).

**Comment by david-eckardt-sociomantic** [comment]
I totally agree with all points, but I don't expect any of this behaviour to be implemented anytime :(

**Comment by mihails-strasuns-sociomantic** [comment]
@don-clugston-sociomantic this is a mixed topic. The fact that original stack trace is no longer relevant is actually very helpful when you design fiber-blocking APIs on top of epoll events. For example, if you have an exception thrown in DHT callback, it is in fact more helpful to see a stack trace leading to `dht.put` line that registered it. But in the case you describe it only makes things worse indeed by abandoning important information.

Sadly, I don't see how anything can be done better with existing fiber and exception design in D (maybe you have some ideas?). Right now approach I advocate is to handle all exceptions within their own task as long as possible - and `exception_handler` acts as a line of last defense. And it shouldn't rethrow - this is simply default behaviour to poorly emulate old semantics. Reasonable `exception_handler` should either consume exception and ignore it (logging the incident) or abort the app immediately.

**Comment by don-clugston-sociomantic** [comment]
I think we should move towards abandoning the old semantics. I think they're just a mistake.

Although it would be possible to integrate fibers into the stack-walking code, so that exception handling works properly across fibers, I think the whole idea of unwinding the stack of a different fiber doesn't actually make much sense.

I think that if an app wants to be able to survive fibers having uncaught exceptions, it should put a Pokemon catch clause in the main function of each fiber.
It sounds to me as though in the case you describe, the fiber which registered the epoll event would want to get notified that the fiber it created has failed. And it might (possibly) want to then throw an exception from that point, but I think it's a different exception, it's handling the fact that the fiber failed, it's not handling the actual error which happened in the fiber.

TL;RD   Can we change the default behaviour? Or give some way to disable the Pokemon clause?

**Comment by mihails-strasuns-sociomantic** [comment]
> I think that if an app wants to be able to survive fibers having uncaught exceptions, it should put a Pokemon catch clause in the main function of each fiber.

That is exactly what `exception_handler` is for - it allows one to inject a generic last resort catch clause for all tasks in the app. I think the main problem is that currently not many apps use it and instead just rely on default (old) semantics which is arguably a worst option.

> TL;RD Can we change the default behaviour?

What would be the new default? The problem we have here is that there are two entirely different classes of apps - some are not allowed to abort and some want to do it as early as possible in case of problem.

**Comment by mihails-strasuns-sociomantic** [comment]
Btw another problem I have noticed when fixing this (and had no idea about previously) is that you actually can't rethrow existing exception from a different call stack (for example, pass it to new function and throw from there). It will result in immediate abort.

**Comment by david-eckardt-sociomantic** [comment]
> you actually can't rethrow existing exception from a different call stack

What?! Not even like this:
```d
Exception e;
try
    throw new Exception;
catch (Exception caught)
    e = caught;
throw e;
```
?

**Comment by mihails-strasuns-sociomantic** [comment]
I don't know. The code responsible for aborting apps is here https://github.com/sociomantic-tsunami/tangort/blob/32ad03f41da038b6e315931c551ddfe4cd0d26eb/src/rt/deh.d#L227 - this branch is taken when function intended to "Given EBP, find return address to caller, and caller's EBP" fails.

Maybe @don-clugston-sociomantic or @iain-buclaw-sociomantic can say if this part of tangort actually behaves as intended?

**Comment by nemanja-boric-sociomantic** [comment]
That `abort()` relies on the fact that there's always going to be Pokemon catch in the `dmain` catching all exceptions. Under the assumption that we're not omitting `PUSH RBP; MOV RBP, SP` while doing the function call, I'm not sure why this would fail? (There's a catch-all in the Fibers entry point, right?) I'm also interested to see what happens in D2, since they've reworked the exception handling on Linux to use DWARF to resolve the exception handlers, and not the frame-walking method.

**Comment by nemanja-boric-sociomantic** [comment]
Interesting is that the original exception object is not used for finding the callers, but just to check if there's an correct catch block to jump to in the current frame. Maybe the method is not re-entrant? I'll try to debug it.

**Comment by mihails-strasuns-sociomantic** [comment]
> There's a catch-all in the Fibers entry point, right?

Not necessarily.
