### ISSUE TITLE
Task.await() with timeout

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#46]
There are many situations where you want to wait for a Task to finish _or_ a certain time to pass. (e.g. connecting to a server with some bail-out logic if the connection isn't promptly established.)

**Comment by joseph-wakeling-sociomantic** [comment]
Just to note: this covers a lot of use-cases, but there will be times when _one_ aspect of a task is a hard blocker but another can be timed out.

I guess the sane behaviour here is that if called without a timeout, `Task.await()` waits for as long as it takes, so it's in the user's hands what is wanted ... ?

**Comment by gavin-norman-sociomantic** [comment]
An example, if I understand what you mean, would be something like awaiting connection to a distributed server. You could do that with something like this:
```D
theScheduler.await(new ConnectToAtLeast(1));
theScheduler.awatOrTimeout(new ConnectToAll, timeout_ms));
```

**Comment by joseph-wakeling-sociomantic** [comment]
Yes, that sounds like a good approach.

**Comment by joseph-wakeling-sociomantic** [comment]
Would also be helpful if it was possible to provide a notification delegate of some kind to handle the cases where (i) the wait ended because the task exited successfully and (ii) the wait ended because the timeout was reached.

**Comment by nemanja-boric-sociomantic** [comment]
Given the tendency of task code to flow linearly, I would think the cleanest option would be just to provide this via return boolean or `out` parameter?

```
auto is_timeout = theScheduler.awaitOrTimeout(...);
if (is_timeout)
{
    // cancel...
}
```

**Comment by gavin-norman-sociomantic** [comment]
Yeah, we can provide a return value.

**Comment by mihails-strasuns-sociomantic** [comment]
@joseph-wakeling-sociomantic @gavin-norman-sociomantic opinion needed - what should happen with awaited task after timeout? Should it be killed or left running (but without resume hook)?

**Comment by gavin-norman-sociomantic** [comment]
Very good point. The important distinction seems to be between tasks which:
1. can safely be allowed to continue and end in their own time,
2. may be simply killed,
3. require some kind of explicit "stop" behaviour.

Type 3 is probably the most tricky and important. An obvious example would be a DHT (neo) GetAll request running in a task. For the task to end, the request must (ideally) be explicitly stopped. Simply killing the task will not do this.

(It's nice that we can publicly refer to our storage components now :)

**Comment by joseph-wakeling-sociomantic** [comment]
My use-case involves the task continuing to run.  The intended timeout is on _waiting for it to complete_, not on it completing at all (if that makes sense).

The particular use cases I have in mind are (i) waiting for a complete DHT handshake and (ii) waiting for `GetAll` request to complete.  In both cases it would be nice to time out on _waiting_ while allowing the procedures to continue until complete.

(Gosh, it feels so liberating to be able to openly discuss this now...)

**Comment by joseph-wakeling-sociomantic** [comment]
I agree with @gavin-norman-sociomantic though that it's probably a good idea to support multiple use cases here, and that it's not obvious that merely killing the task is sufficient in all cases where we want things to just stop.

**Comment by joseph-wakeling-sociomantic** [comment]
A thought that occurs: just as we make tasks responsible for copying their input data in an appropriate way, why not make tasks responsible for defining the mechanisms required to safely kill them?  (One can still have a hard-kill-upon-further-timeout.)

I suppose the caveat here is that it might still be a use-case-by-use-case requirement, and that it's probably safer to force the user to confront the question: "You must tell us how to safely kill this task" (explicitly, every time) rather than to assume that the user will provide a task with a correct built-in kill mechanism.

**Comment by mihails-strasuns-sociomantic** [comment]
Important note - requiring explicit "stop" is not something scheduler need to be aware of because you can catch `TaskKillException` at the top of your `run` method in specific task to do any custom "stop" thing before rethrowing.

The main question is about tasks that need to keep running in the background, like DHT handshake, after initial timeout. When I think about it, such tasks seem to be more typical than tasks that should die completely on timeout - and because of that I am leaning towards opinion that it should be the default.

If one wants to still kill the task upon timeout, it is possible to check return value of `awaitOrTimeout` and kill task manually anyway.

**Comment by mihails-strasuns-sociomantic** [comment]
(I have moved the milestone because implementing this is certain to require some back and forth discussion and 2.10 is on its way)

**Comment by gavin-norman-sociomantic** [comment]
What you say sounds like a reasonable point to start from.

**Comment by joseph-wakeling-sociomantic** [comment]
> When I think about it, such tasks seem to be more typical than tasks that should die completely on timeout - and because of that I am leaning towards opinion that it should be the default.

Yes, agree.  Explicitly killing a task on timeout should be the exception (pun intended...), not the default.

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/234
